language: go
env:
   - GO111MODULE=on
go:
   - "1.12"
install:
   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
script:
   - bash check.sh
after_success:
   - bash <(curl -s https://codecov.io/bash)

